### ISSUE TITLE
Panic after Update to 0.4.0

### ISSUE THREAD

**Issue by ivaquero** [jomaway/typst-linguify#5]
Hi, I updated to 0.4.0, and came cross panic

First, I have to mention the README has not been updated.

In my template, I use `set-database(toml("lang.toml"))` instead of `linguify_set_database(toml("lang.toml"))`, then I got the following error

```typ
panic("Could not find a section for the language (" + selected_lang + ") in the linguify database.")
```

BTW, my `lang.toml` is

```
[conf]
default-lang = "zh"

[lang.zh]
chapter = "章节"
content = "主要内容"
definition = "定义"
theorem = "定理"
lemma = "引理"
```

**Comment by jomaway** [comment]
I tried to replicate your error, but it works fine on my side. Could you please set up an typst project with the error online and send me the link to that?

**Comment by ivaquero** [comment]
I fixed the issue by updating the `lang.toml` format. Thank you again for this wonderful package!
