### ISSUE TITLE
Version and README mismatch between main repo and Typst Universe

### ISSUE THREAD

**Issue by xkevio** [jomaway/typst-linguify#8]
This repository currently has linguify at v0.4.0 inside the `typst.toml` whereas it is on v0.4.1 in Typst Universe.
Furthermore, the examples on Typst Universe are incorrect as they do not use `[lang.de]` but rather `[de]` inside the translations TOML file which leads to compilation errors. Those examples also import the v0.4.0 version.

PS: The semicolon after `set-database(...)` in the examples is also superfluous and could be removed.

**Comment by jomaway** [comment]
Thanks. I know this package needs some love. It's on my to-do list. But I am short of time right now.

If you want to open a PR I am happy to merge it.

**Comment by xkevio** [comment]
I can definitely open a PR to fix the mismatch here! Though I don't know if I can do the PR to typst-universe as that probably has to happen as the maintainer doing it?
